# Generated by Django 5.1.7 on 2025-03-13 13:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(default='', max_length=254)),
                ('authors', models.CharField(default='', max_length=254)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=254)),
                ('Email', models.EmailField(max_length=254)),
                ('Objet', models.CharField(max_length=254)),
                ('Message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('screenplay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.screenplay')),
                ('breakdown', models.URLField()),
            ],
        ),
    ]
